name: Master CI/CD
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.6
      - name: Compile
        run: mvn clean compile --file pom.xml -B -U -T 1.5C
      - name: Build
        run: mvn clean package --file pom.xml -B -U -T 1.5C -DskipTests
      - name: Test
        run: mvn clean verify --file pom.xml -B -U -T 1.5C
      - name: Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: mvn clean deploy --file pom.xml -B -U -T 1.5C -P ci-cd -DskipTests
